#!/usr/bin/env zsh

flatpak install flathub org.telegram.desktop -y
flatpak install flathub com.sublimetext.three -y
flatpak install flathub org.gnome.Builder -y
flatpak install flathub org.mozilla.Thunderbird -y
flatpak install flathub eu.betterbird.Betterbird -y
flatpak install flathub com.axosoft.GitKraken -y
flatpak install flathub com.discordapp.Discord -y
flatpak install flathub com.google.Chrome -y
flatpak install flathub com.spotify.Client -y
flatpak install flathub com.brave.Browser -y
flatpak install flathub org.onlyoffice.desktopeditors -y
flatpak install flathub org.kde.krita -y
flatpak install flathub org.inkscape.Inkscape -y
flatpak install flathub org.audacityteam.Audacity -y
flatpak install flathub com.getpostman.Postman -y
flatpak install flathub rest.insomnia.Insomnia -y
flatpak install flathub io.beekeeperstudio.Studio -y
flatpak install flathub md.obsidian.Obsidian -y
flatpak install flathub com.redis.RedisInsight -y
flatpak install flathub com.sublimemerge.App -y
flatpak install flathub com.mattjakeman.ExtensionManager -y
flatpak install flathub com.github.tchx84.Flatseal -y
flatpak install flathub org.onlyoffice.desktopeditors -y
flatpak install flathub org.kde.kdenlive -y
flatpak install flathub org.kde.krita -y
flatpak install flathub io.github.giantpinkrobots.flatsweep -y
flatpak install flathub io.missioncenter.MissionCenter -y
flatpak install flathub org.wireshark.Wireshark -y